#!/bin/bash

# set -eux -o pipefail

source ./sensetive

function isHeadsetConnected {
  bluetoothctl info "$HEADSET_MAC" | grep 'Connected' | awk '{print $2}'
}

function isControllerPowered {
  bluetoothctl show | grep 'Powered' | awk '{print $2}'
}

function isBluetooth {
  systemctl is-active bluetooth
}

function isBlocked {
  rfkill -no device,soft | awk -v dev="$BLUETOOTH" '$1 == dev {print $2}'
}

function connectHeadset {
  bluetoothctl connect "${HEADSET_MAC}" | grep -c 'Failed'
}

debug3() {
  if [[ "$1" == "debug" || "$2" == "debug" ]]; then
    local name="$3";
    clr_green "DEBUG | $name"
  fi
}


